### ISSUE TITLE
Model Performance

### ISSUE THREAD

**Issue by basavarajsh98** [scutcsq/DWFormer#10]
Hi,

It is mentioned in the paper that the model was trained for 120 epochs. However, during our testing, the model is converging well under 30 epochs with performance close to what is reported in your paper. Is this something that you observed as well? Since there are no learning curves provided in the paper, it would be great if you could let us know if you employed early stopping during your experiments.

Also, will you be releasing the pretrained model anytime soon?

Thanks,

**Comment by scutcsq** [comment]
Hello, thanks for your question. It is the same situation as you run and I do not provide early stopping. You can use the early stop stop method.
Since the training process is clear, so we will not provide the pretrained checkpoint.
