### ISSUE TITLE
Vanilla_Transformer and localTranformer2 

### ISSUE THREAD

**Issue by jhwang2042** [scutcsq/DWFormer#11]
Hello, I am very interested in your project, but I couldn't find descriptions for the Vanilla_Transformer and localTranformer2 methods in the code.

**Comment by 18wangsss** [comment]
在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？

**Comment by 18wangsss** [comment]
> 在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？



> Hello, I am very interested in your project, but I couldn't find descriptions for the Vanilla_Transformer and localTranformer2 methods in the code.

在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？

**Comment by jhwang2042** [comment]
> > 在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？
> 
> > Hello, I am very interested in your project, but I couldn't find descriptions for the Vanilla_Transformer and localTranformer2 methods in the code.
> 
> 在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？

你好，可以加个qq吗

**Comment by jhwang2042** [comment]
> > > 在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？
> > 
> > 
> > > Hello, I am very interested in your project, but I couldn't find descriptions for the Vanilla_Transformer and localTranformer2 methods in the code.
> > 
> > 
> > 在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？
> 
> 你好，可以加个qq吗
540774255

**Comment by scutcsq** [comment]
> > 在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？
> 
> > Hello, I am very interested in your project, but I couldn't find descriptions for the Vanilla_Transformer and localTranformer2 methods in the code.
> 
> 在IEMOCAP中有vanillatransformer.py，里面描述的是Vanilla_Transformer模块。问一下，你有发现论文中提到的IC模块吗？

IC模块部分的计算可以参照MHA里面haltingscore的计算方式来，代码实现里我没有单独将这部分独立出来。

**Comment by scutcsq** [comment]
> Hello, I am very interested in your project, but I couldn't find descriptions for the Vanilla_Transformer and localTranformer2 methods in the code.

您好，localtransformer部分的代码我后续会上传，近期比较忙没有太多时间管理仓库哈！
