### ISSUE TITLE
关于模型训练的问题

### ISSUE THREAD

**Issue by Songsong0824** [scutcsq/DWFormer#12]
您好，请问整个训练流程大概需要多少时间

**Comment by 18wangsss** [comment]
> 您好，请问整个训练流程大概需要多少时间

冒昧问一下，你在代码里面找到IC模块了吗

**Comment by scutcsq** [comment]
我在IEMOCAP训练的时间是差不多六个小时，在Meld上是差不多三个小时

**Comment by Songsong0824** [comment]
> 我在IEMOCAP训练的时间是差不多六个小时，在Meld上是差不多三个小时

好的，谢谢您！
