### ISSUE TITLE
some questions about the paper

### ISSUE THREAD

**Issue by Songsong0824** [scutcsq/DWFormer#15]
@scutcsq Hello professor, your article has been very helpful to me, but I noticed some issues while reading. In the description of DLWT in Chapter 2, is it supposed to be A strong emotional correlation windows and B weak emotional correlation windows?In my future work, I'll also be referencing your article. Could you please help clarify any questions my students may have about it?

**Comment by scutcsq** [comment]
Hello, Thank you for the correction, I am sorry for making such an error in writing the paper.

**Comment by Songsong0824** [comment]
谢谢您的回复~还想请问一下您IC模块的代码实现具体在哪个文件中呢

**Comment by scutcsq** [comment]
我融到具体的注意力机制模块里了，没有单独写出来，你看各个Attention里面应该是有的

**Comment by Songsong0824** [comment]
> 我融到具体的注意力机制模块里了，没有单独写出来，你看各个Attention里面应该是有的

好的，谢谢您！
