### ISSUE TITLE
关于复现结果的问题

### ISSUE THREAD

**Issue by Songsong0824** [scutcsq/DWFormer#16]
您好，我复现了您的实验，但是结果略有差距，IECMOCAP数据集相差不多，但MELD上相差有点多 @scutcsq 
![MELD train+valid](https://github.com/scutcsq/DWFormer/assets/151549324/60b4577e-1202-4541-bd7b-370cf1108e0c)
![train5 valid5 +五折交叉验证](https://github.com/scutcsq/DWFormer/assets/151549324/615c375f-272f-4ff1-b414-6b2689f26752)

**Comment by scutcsq** [comment]
我是取多个种子平均的结果，随机种子对实验结果也会有一些浮动的影响哈

**Comment by Songsong0824** [comment]
好，谢谢您的回答
