### ISSUE TITLE
csv

### ISSUE THREAD

**Issue by wp220517** [scutcsq/DWFormer#2]
#IEMOCAP:
for i in range(1,6):
    csv = r'/148Dataset/data-chen.shuaiqi/IEMOCAP/IEMOCAP_full_release/data'
    inputdir = r'/148Dataset/data-chen.shuaiqi/IEMOCAP/IEMOCAP_full_release/Session'
    outputdir = r'/148Dataset/data-chen.shuaiqi/IEMOCAP/IEMOCAP_full_release/Feature/WavLM/Session'
    dir = inputdir + str(i) + r'/sentences/wav/'
    csvs = csv + str(i) + '.csv'
    csv = pd.read_csv(csvs)
    name1 = csv.dataname.values
    name2 = csv.newdataname.values
您好，请问一下在数据处理阶段中的csv 文件是哪一个？
上述代码中的 csv = r'/148Dataset/data-chen.shuaiqi/IEMOCAP/IEMOCAP_full_release/data'，这个data数据怎么处理的

**Comment by scutcsq** [comment]
您好！
#csv 文件存放于同文件夹目录下的./iemocap_data/
