### ISSUE TITLE
Visualization Results

### ISSUE THREAD

**Issue by whh07141** [scutcsq/DWFormer#20]
您好！我对你们在icassp2023的工作DWFormer非常感兴趣，在paper中您展示了一个可视化DWFormer对于情感相关语音信息在时序序列中不同强度得分的图(Figure 5)。根据我的理解是从DWFormer block最后输出的importance score和阈值thresholds来判断当前帧是否与情感信息强相关，不知道我这样理解是否正确。另外，您方便提供下您如何绘制改图的相关代码吗？我的理解是在通过上述方式可以获取语音情感信息强相关的音频在时序上的长度和起始时间？

**Comment by silent55430394** [comment]
理解是对的，代码绘制我其实是直接把每个token的情感强度保存后用excel绘制的图片
