### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'iemocap_data/data1.csv'

### ISSUE THREAD

**Issue by wangjialin97** [scutcsq/DWFormer#3]
在执行Feature_Extractor/data_preprocess.py文件时，缺少文件[Errno 2] No such file or directory: 'iemocap_data/data1.csv'，请问这个文件应该怎么获取

**Comment by scutcsq** [comment]
您好，datax.csv是trainx.csv和validx.csv的合并文件，对应的datax.csv文件已上传
