### ISSUE TITLE
ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by wangjialin97** [scutcsq/DWFormer#4]
您好，我在运行/IEMOCAP/tran.py时出现此错误，我注意到/IEMOCAP/model.py中DWFormer的forward函数仅return一个值，但是/IEMOCAP/tran.py的108行接收4个值，请问这里是不是有些问题，报错如下：

Traceback (most recent call last):
  File "train.py", line 108, in <module>
    out, attn, windowattn, ML = model(datas, mask)
ValueError: too many values to unpack (expected 4)

**Comment by scutcsq** [comment]
改成out = model(datas, mask)即可
