### ISSUE TITLE
How graphics are drawn？

### ISSUE THREAD

**Issue by MF-XU** [scutcsq/DWFormer#7]
Dear author, I would like to ask you how to draw the visualization diagram for comparison between Vanilla Transformer, Fixed Window Transformer, ATDA and DWFormer models in your paper. Is there any corresponding code?
![417f732e888ceda5073e5589aee37ac](https://github.com/scutcsq/DWFormer/assets/102813678/539eb6be-001a-4f03-bbe7-35f20bbf375d)

**Comment by scutcsq** [comment]
I am sorry that I forget the place to save the corresponding code. You can save the result from the last attention layer from the DWFormer model(like attn13 in IEMOCAP/model.py) and use the matplotlib.pyplot to draw the result... The results from the ATDA, Vanilla Transformer and Fixed Window Transformer are also gathered from the output of the last attention weights.
