### ISSUE TITLE
Data processing problem

### ISSUE THREAD

**Issue by MF-XU** [scutcsq/DWFormer#9]
Dear author, hello. I am a second year graduate student majoring in Electronic Information at Xinjiang University. Thank you for your previous help. When debugging my model based on your code, I would like to change the data processing part of the code. However, I have encountered a problem and would like to discuss it privately with you. I hope to receive your personal contact information so that I can easily ask you some questions in the future. I can leave my email, or you can give me your email, and we can also add WeChat. This issue has been bothering me for a few days now, and I hope to receive your guidance. Thank you very much!

**Comment by scutcsq** [comment]
You can send mails to 202121013939@mail.scut.edu.cn
